---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: pageviews
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 1
  configs:
    message.timestamp.type: "LogAppendTime"
  kafkaRest:
    endpoint: <REST_endpoint>
    kafkaClusterID: <cluster_ID>
    authentication:
      type: basic
      basic:
        secretRef: ccloud-credentials-basic
